"""LRC format utilities: write timestamped and untimestamped lyrics files.

LRC reference (extended/LRC-compatible):
    [ti:Title]
    [ar:Artist]
    [al:Album]
    [length:03:21]
    [00:12.34]First line of lyrics
    [00:15.67]Second line

Unsynced lyrics are written with a `length:` header but no timestamps in the
body, which renders correctly in foobar2000, AIMP, PowerAmp, MusicBee, and
Vanilla.  Some lightweight mobile players (Musicolet, default Android) handle
this gracefully as well.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

# Synced-line prefix: [mm:ss] or [mm:ss.ff] or [mm:ss.fff]
_TIMESTAMP_RE = re.compile(r"^\s*\[(\d{1,2}):(\d{1,2})(?:[\.:](\d{1,3}))?\]")


@dataclass
class LRCDocument:
    """In-memory representation of an LRC file.

    ``lines`` is a list of (timestamp_str, text) pairs.  An empty timestamp
    string ("") marks an unsynced line at the top of the body.

    ``composer``, ``language``, ``year`` and ``tool`` are optional
    "liner-notes" template tags.  ``tool`` is rendered as
    ``[tool:LyricsFAG X.Y.Z]`` when set; the other three are rendered
    conditionally only when the corresponding field is populated.
    Empty values are intentionally the default so legacy LRCDocument
    callers continue to emit exactly the pre-v1.2.1 header set.
    """

    title: str = ""
    artist: str = ""
    album: str = ""
    length_seconds: float = 0.0
    lines: list[tuple[str, str]] = field(default_factory=list)
    diagnostic_lines: list[str] = field(default_factory=list)
    composer: str = ""
    language: str = ""
    year: int = 0
    tool: str = ""

    def add(self, timestamp: str, text: str) -> None:
        self.lines.append((timestamp.strip(), text.strip()))


def format_duration(seconds: float) -> str:
    """Format seconds as ``mm:ss`` (LRC ``length:`` style)."""
    if seconds <= 0:
        return "00:00"
    total = int(round(seconds))
    m, s = divmod(total, 60)
    return f"{m:02d}:{s:02d}"


def format_timestamp_ms(ms: int) -> str:
    """Format an integer millisecond timestamp as ``mm:ss.cc`` (LRC body).

    Centiseconds (2 digits after the dot) is the most portable LRC precision:
    foobar2000, AIMP, MusicBee, foobar2000 mobile, Vanilla, and Musicolet all
    accept it.  Anything finer (milliseconds, frames) is ignored by older
    players and rounds away the granularity we actually need for lyrics.
    """
    if ms < 0:
        ms = 0
    cs = ms // 10
    m, cs = divmod(cs, 6000)  # 6000 centiseconds per minute
    s, cs = divmod(cs, 100)
    return f"{m:02d}:{s:02d}.{cs:02d}"


def write_lrc(
    path: Path,
    document: LRCDocument,
    *,
    overwrite: bool = True,
) -> None:
    """Serialize an LRCDocument and write it to ``path``.

    Raises ``FileExistsError`` when the target exists and ``overwrite`` is
    False; otherwise overwrites atomically via a temporary file.
    """
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists (pass overwrite=True)")

    body = _serialize(document)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(body, encoding="utf-8")
    tmp.replace(path)


def _serialize(doc: LRCDocument) -> str:
    parts: list[str] = []
    if doc.title:
        parts.append(f"[ti:{doc.title}]")
    if doc.artist:
        parts.append(f"[ar:{doc.artist}]")
    if doc.album:
        parts.append(f"[al:{doc.album}]")
    # Liner-notes template fields.  Rendered in a stable order between
    # [al:] and [length:] so the file still looks like a stock LRC
    # to the parser in :func:`header_lines`, and so a downstream
    # tool / player that walks the headers in order sees the same
    # sequence every time.  Each header is conditional so an
    # under-tagged audio file only emits the fields it actually has
    # populated; ``tool`` is unconditional within ``if doc.tool``
    # so the producer credit vanishes if a caller explicitly opts
    # out by clearing ``tool``.
    if doc.composer:
        parts.append(f"[au:{doc.composer}]")
    if doc.language:
        parts.append(f"[lang:{doc.language}]")
    if doc.year > 0:
        parts.append(f"[year:{doc.year}]")
    if doc.tool:
        parts.append(f"[tool:{doc.tool}]")
    if doc.length_seconds > 0:
        parts.append(f"[length:{format_duration(doc.length_seconds)}]")

    # Producer diagnostics (``[# generated by <provider>; key=value; ...]``)
    # go between the standard headers and the body so users can audit which
    # provider produced the lyrics without these lines bleeding into lyric
    # content.  See ``LRCDocument.diagnostic_lines`` docstring for the
    # parser-safety note.  ``or []`` defends against a future caller
    # passing ``None`` (the dataclass default is already ``[]``).
    parts.extend(doc.diagnostic_lines or [])
    parts.append("")  # blank line separator before body

    for ts, text in doc.lines:
        if ts:
            parts.append(f"[{ts}]{text}")
        else:
            parts.append(text)
    parts.append("")  # trailing newline
    return "\n".join(parts)


def split_synced_text(lrc_text: str) -> list[tuple[str, str]]:
    """Parse raw LRC text into [(timestamp_str, lyric_text), ...].

    Returns timestamps in ``mm:ss`` form (the fractional part is dropped to
    keep things compatible with the simplest LRC parsers; centiseconds are
    preserved by the source string itself).
    """
    out: list[tuple[str, str]] = []
    for raw in lrc_text.splitlines():
        line = raw.rstrip()
        if not line:
            continue
        m = _TIMESTAMP_RE.match(line)
        if not m:
            continue
        mm, ss, _frac = m.groups()
        ts = f"{int(mm):02d}:{int(ss):02d}"
        text = line[m.end():].strip()
        out.append((ts, text))
    out.sort(key=lambda pair: pair[0])
    return out


def header_lines(lrc_text: str) -> dict[str, str]:
    """Return ID3-style headers (``[key:value]`` lines) from raw LRC text.

    Synced lines are excluded via the timestamp gate, so only real headers
    (``[ti:..]``, ``[ar:..]``, ...) come back.
    """
    headers: dict[str, str] = {}
    for raw in lrc_text.splitlines():
        if _TIMESTAMP_RE.match(raw):
            continue
        m = re.match(r"^\[([a-zA-Z]+):(.*)\]\s*$", raw.strip())
        if not m:
            continue
        headers[m.group(1).lower()] = m.group(2).strip()
    return headers


__all__: Iterable[str] = (
    "LRCDocument",
    "format_duration",
    "format_timestamp_ms",
    "header_lines",
    "split_synced_text",
    "write_lrc",
)
