"""Lyrics fetchers with a chained fallback strategy.

Defaults to LRCLIB first (returns synced lyrics natively -> best LRC output)
and falls back to Genius (huge database, unsynced plain text).  Either
provider can be selected exclusively via ``LyricsFetcher(source="...")``.

Network errors and empty results are tolerated; both providers log their
decisions so the caller can surface a "skipped: <reason>" message.
"""

from __future__ import annotations

import logging
import threading
from dataclasses import dataclass, field
from typing import Iterable, Optional

import re
from itertools import islice
import requests

try:
    import lyricsgenius  # type: ignore
except ImportError:  # pragma: no cover - optional at runtime
    lyricsgenius = None  # type: ignore[assignment]

from .audio import AudioFile
from .lrc import LRCDocument, split_synced_text

LOG = logging.getLogger(__name__)

LRCLIB_BASE = "https://lrclib.net/api"
LRCLIB_TIMEOUT = 15
LRCLIB_USER_AGENT = "LyricsFAG/0.1 (https://github.com/local/lyricsfag)"

# Genius API access token (free at https://genius.com/api-clients).  When
# omitted, the library silently skips Genius and reports "no token".
ENV_GENIUS_TOKEN = "GENIUS_ACCESS_TOKEN"

# Human-readable marker prepended to ``diagnostic_lines`` whenever the
# lyrics came from local ``faster-whisper`` transcription.  The square-
# bracket-hash form matches the existing ``[# ...]`` line convention so
# :func:`split_synced_text` and :func:`header_lines` skip it (they
# neither match the ``[mm:ss]`` timestamp gate nor the
# ``[a-zA-Z]+:..]`` ID3 header regex).  See
# :func:`_format_diagnostics` for the parser-safety contract.
WHISPER_PROVIDER_MARKER = "[# Generated Lyrics with Whisper]"
# Variant emitted when Whisper ran on vocals pre-isolated by Demucs; the
# .lrc reader sees ONE human-readable line, so we encode the pipeline
# distinction in the label rather than dumping a second diagnostic.
WHISPER_DEMUCS_PROVIDER_MARKER = "[# Generated Lyrics with Demucs + Whisper]"

# Provider name emitted by :class:`FasterWhisperAnalyzer`.  Centralised
# here so the GUI / CLI / LRC writers don't drift if the analyzer is
# ever renamed -- one constant change keeps the marker logic in sync.
WHISPER_PROVIDER_NAME = "whisper"


def _extract_name(field_val, default: str = "") -> str:
    """Coerce ``Song.primary_artist`` / ``Song.album`` into a plain name.

    ``lyricsgenius >= 3`` stores nested Genius entities (``primary_artist``,
    ``album``, etc.) as raw dicts carved straight from the JSON API response --
    not as ``Artist``/``Album`` instances.  Older fixtures, mocked responses, or
    future versions may return object instances with a ``.name`` attribute.
    This helper accepts both shapes (and ``None``/``str``) and returns the
    human-readable name.
    """
    if not field_val:
        return default
    if isinstance(field_val, str):
        return field_val or default
    if isinstance(field_val, dict):
        name = field_val.get("name")
        return name if isinstance(name, str) and name else default
    # Object-like (custom class with a ``name`` attribute)
    name = getattr(field_val, "name", None)
    if isinstance(name, str) and name:
        return name
    return default


def _format_diagnostics(result: "LyricsResult") -> list[str]:
    """Render a ``LyricsResult``'s provenance as a single ``[# ...]`` line.

    Output format::

        [# generated by <provider>; <sorted-key>=<value>; ...]

    When ``raw_extras`` is empty we still emit a provider-only line so the
    LRC carries a consistent provenance marker for every successful result
    (LRCLIB / Genius / heuristic / whisper / vad-preflight).

    Non-scalar extras (``None``, ``list``, ``dict``, ``set``, ``tuple``,
    ``Decimal``, ``UUID``, ``Path``, ``bytes``, ``datetime``, ...) and scalar
    values whose string form is empty or contains ``;`` or ``]`` are dropped
    with a ``LOG.warning``.  The format has no quoting, so a stray separator
    would corrupt the single ``[# ...]`` line and break the parser-safety
    guarantee below.

    The ``provider`` name is filtered the same way: empty, or ``;``/``]``,
    cause the entire diagnostic line to be suppressed (without a parsable
    provider there's nothing safe to record).

    Provider authors should keep ``raw_extras`` keys lowercase so the
    sorted-by-key iteration produces stable diffs across runs.    Conventional LRC parsers ``split_synced_text`` and ``header_lines``
    already skip ``[# ...]`` lines (their regexes demand ``[mm:ss]``
    timestamps or ``[a-zA-Z]+:..]`` headers respectively), so the
    diagnostic never bleeds into the visible lyric stream.
    """
    provider = result.provider or ""
    if not provider or ";" in provider or "]" in provider:
        LOG.warning(
            "diagnostic: dropping entire line; empty or unsafe provider name %r",
            provider,
        )
        return []
    # Whisper diagnostics are intentionally curtailed here: the human-
    # readable ``WHISPER_PROVIDER_MARKER`` (or its ``Demucs +`` variant)
    # already tells the reader where the synth lyrics came from, and the
    # verbose ``compute_type``/``device``/``duration``/... line is too
    # noisy for a file the user opens in their music player. ``raw_extras``
    # itself stays populated so non-LRC consumers (logger, GUI status)
    # keep the underlying detail. Other providers (LRCLIB, Genius,
    # heuristic, vad-preflight) keep the original verbose line because
    # they have no equivalent friendly marker.
    if provider == WHISPER_PROVIDER_NAME:
        return []
    extras: list[str] = [] 
    for key, value in sorted(result.raw_extras.items()):
        if not isinstance(value, (str, int, float, bool)):
            LOG.warning(
                "diagnostic: dropping non-scalar extra %s=%r",
                key, value,
            )
            continue
        rendered = str(value)
        if not rendered or ";" in rendered or "]" in rendered:
            LOG.warning(
                "diagnostic: dropping empty or unsafe extra %s=%r",
                key, value,
            )
            continue
        extras.append(f"{key}={rendered}")
    if extras:
        return [f"[# generated by {provider}; " + "; ".join(extras) + "]"]
    return [f"[# generated by {provider}]"]


@dataclass
class LyricsResult:
    """Successful response from a provider.

    ``synced_lines`` is the list of (timestamp_str, text) pairs; empty if the
    result is unsynced (e.g. from Genius).  ``source`` records which provider
    produced the data for later logging.
    """

    provider: str
    title: str
    artist: str
    album: str = ""
    length_seconds: float = 0.0
    synced_lines: list[tuple[str, str]] = field(default_factory=list)
    plain_text: str = ""
    instrumental: bool = False
    raw_extras: dict = field(default_factory=dict)

    @property
    def is_synced(self) -> bool:
        return bool(self.synced_lines)

    def to_document(self) -> LRCDocument:
        """Convert this result into an :class:`LRCDocument` ready for writing."""
        diagnostics: list[str] = _format_diagnostics(self)
        # When this result came from local faster-whisper transcription,
        # prepend a stable, human-readable marker so anyone reading the
        # .lrc file can tell at a glance that the lyrics are synthetic
        # and may need a manual pass for accuracy.  When the run also
        # went through Demucs vocal isolation, the label spells that out
        # so the reader knows the pipeline ordered differently than a
        # plain Whisper pass.  ``vocal_isolation`` is set by
        # :class:`FasterWhisperAnalyzer` to ``"demucs"`` or ``"raw"``;
        # any future value (or a missing key) falls back to the plain
        # Whisper marker rather than guessing.  The marker is the only
        # diagnostic line for Whisper -- ``_format_diagnostics`` no
        # longer emits the structured ``[# generated by whisper; ...]``
        # line, which kept ``compute_type``/``device``/``duration``/... in
        # the user's .lrc file but added nothing actionable for them.
        if self.provider == WHISPER_PROVIDER_NAME:
            if self.raw_extras.get("vocal_isolation") == "demucs":
                diagnostics.insert(0, WHISPER_DEMUCS_PROVIDER_MARKER)
            else:
                diagnostics.insert(0, WHISPER_PROVIDER_MARKER)
        doc = LRCDocument(
            title=self.title,
            artist=self.artist,
            album=self.album,
            length_seconds=self.length_seconds,
            diagnostic_lines=diagnostics,
        )
        if self.synced_lines:
            doc.lines = list(self.synced_lines)
        elif self.plain_text:
            for line in self.plain_text.splitlines():
                doc.add("", line)
        return doc


@dataclass
class LyricsFailure:
    provider: str
    reason: str


# ---------------------------------------------------------------------------
# LRCLIB client
# ---------------------------------------------------------------------------


class LRCLIBClient:
    """Thin wrapper over the public LRCLIB.net API."""

    def __init__(self, session: Optional[requests.Session] = None) -> None:
        self.session = session or requests.Session()
        self.session.headers.setdefault("User-Agent", LRCLIB_USER_AGENT)

    def get(
        self,
        *,
        artist: str,
        title: str,
        album: str = "",
        duration: float = 0.0,
    ) -> LyricsResult | LyricsFailure:
        url = f"{LRCLIB_BASE}/get"
        params = {
            "artist_name": artist,
            "track_name": title,
        }
        if album:
            params["album_name"] = album
        if duration > 0:
            params["duration"] = int(round(duration))

        try:
            resp = self.session.get(url, params=params, timeout=LRCLIB_TIMEOUT)
        except requests.RequestException as exc:
            return LyricsFailure("lrclib", f"network error: {exc}")

        if resp.status_code == 404:
            return LyricsFailure("lrclib", "no match")
        if resp.status_code == 429:
            return LyricsFailure("lrclib", "rate limited")
        if resp.status_code >= 500:
            return LyricsFailure("lrclib", f"server error {resp.status_code}")
        if not resp.ok:
            return LyricsFailure("lrclib", f"HTTP {resp.status_code}")

        try:
            data = resp.json()
        except ValueError as exc:
            return LyricsFailure("lrclib", f"bad json: {exc}")
        if not isinstance(data, dict):
            return LyricsFailure("lrclib", "unexpected payload shape")

        synced = (data.get("syncedLyrics") or "").strip()
        plain = (data.get("plainLyrics") or "").strip()

        if not synced and not plain:
            return LyricsFailure("lrclib", "empty payload")

        return LyricsResult(
            provider="lrclib",
            title=data.get("trackName") or title,
            artist=data.get("artistName") or artist,
            album=data.get("albumName") or album,
            length_seconds=float(data.get("duration") or duration or 0),
            synced_lines=split_synced_text(synced) if synced else [],
            plain_text=plain if not synced else "",
            instrumental=plain.lower() in {"[instrumental]", "instrumental"},
            # Filter empty values out of ``raw_extras`` so the defensive
            # ``_format_diagnostics`` doesn't fire its
            # ``diagnostic: dropping empty or unsafe extra`` WARNING for
            # LRCLIB responses that lack the optional ``url`` field
            # (lrclib.net doesn't always fill it in -- without this gate
            # every such hit would warn once per file).  Both ``id`` and
            # ``lrclib_url`` are filtered the same way so the syntax
            # stays uniform -- a missing ``id`` is rare but the
            # comprehension handles both cases with no extra cost.
            raw_extras={
                k: v for k, v in (
                    ("id", data.get("id")),
                    ("lrclib_url", data.get("url") or ""),
                )
                if v
            },
        )


# ---------------------------------------------------------------------------
# Genius client
# ---------------------------------------------------------------------------


# Detect Genius "list/index" wiki pages that come back from
# ``lyricsgenius.search_song`` when the user's audio tags happen to match
# a wiki article rather than an actual song (real example observed:
# ``"List of Virtual YouTubers (VTubers)"`` by ``"Genius Japan"`` matched
# an audio file whose tags resolved to that page; the resulting .lrc was
# ~2200 lines of `Name / JapaneseName (ProductionGroup)` entries).
#
# The detector uses two *binary* signals -- no density thresholds --
# because density-based heuristics have repeatedly false-positived on
# legitimate rap/feature-heavy tracks.  The signals are:
#
# 1. **Alphabet navigation header**: Genius table-of-contents / alphabetical
#    indexes render as many adjacent single-character (or single-symbol)
#    lines at the very top of the page body.  No real song lyric body
#    starts with this pattern; the worst case would be a song that quotes
#    the alphabet in a verse, which uses ``A, B, C, D`` on a single line
#    rather than 26 separate single-character lines.
#
# 2. **Long-body cap**: a hard ceiling on the number of LF characters
#    (cheap O(N) ``count`` -- good enough since ``lyricsgenius`` returns
#    LF- or CRLF-normalised text).  Bumped to 1000 after review so a
#    labelled-section-heavy long song (``Rap God`` ~300 lines in
#    ``lyricsgenius``' output) stays comfortably below the threshold.
_GENIUS_INDEX_HEAD_LEN = 30
_GENIUS_INDEX_HEAD_MIN_SINGLE_CHARS = 8
_GENIUS_INDEX_MAX_LINES = 1000


# Reject Genius "wrong song" auto-corrects: even after the index-page
# filter above, Genius will happily return a popular song whose
# title/artist *partially* match the query when the user actually
# wanted a different (less popular) one.  Token-set Overlap Coefficient
# ``|A ∩ B| / min(|A|, |B|)`` is the right metric here -- Jaccard
# penalises subset matches like ``{beatles} ⊆ {the, beatles}``, but
# Overlap Coefficient forgives them (returns 1.0).  The same forgiving
# behaviour handles ``(Acoustic)``, ``feat. X``, ``- Remastered 2009``,
# ``(Live at Wembley)``, etc. when query tokens are a subset of the
# response tokens, while still rejecting genuinely different songs.
#
# Common release-variant markers are dropped at tokenisation so they do
# not inflate the smaller set and unfairly fail real matches.  They
# matter to a listener looking for a specific release but do NOT
# change song identity for "give me the lyrics" use case.
_GENIUS_MATCH_THRESHOLD = 0.5
_GENIUS_MATCH_STOPWORDS = frozenset({
    # English articles + prepositions.  Drop "the" so ``The Beatles``
    # tokens as just ``{beatles}`` (forgiving for non-The query), and
    # drop "in"/"of"/"on"/"at"/"from" so venue/positional suffixes like
    # ``"Live in Concert"`` / ``"From the Inside"`` don't inflate the
    # smaller overlap set and false-pass a wrong-song query.
    "the", "a", "an", "in", "of", "on", "at", "from",
    # Featured-artist markers
    "feat", "ft", "featuring", "with",
    # Release-variant markers -- irrelevant to song identity for lyrics use
    "remastered", "remaster", "remasterisation", "remasterization",
    "live", "acoustic", "unplugged", "radio", "edit", "edition",
    "version", "remix", "mix", "demo", "take",
    # Misc noise seen on Genius album pages
    "original", "single", "album", "ost",
})


def _genius_match_tokens(text: str) -> set[str]:
    """Tokenise ``text`` for the song-mismatch overlap check.

    All non-alphanumerics become spaces so ``Yesterday (Acoustic)``,
    ``Yesterday-Remastered``, and ``Yesterday feat. X`` all tokenise
    consistently (``yesterday``, ``yesterday``, ``yesterday`` / ``x``
    respectively).  Empty input returns an empty set so the caller can
    distinguish "no title given" from "title with no real words".
    """
    if not text:
        return set()
    cleaned = re.sub(r"[^\w\s]+", " ", text, flags=re.UNICODE).lower()
    # ``"".split()`` never returns empty strings; the ``in`` membership
    # test against the stopword frozenset handles token filtering.
    return {tok for tok in cleaned.split() if tok not in _GENIUS_MATCH_STOPWORDS}


def _overlap_coef(a: set[str], b: set[str]) -> float:
    """Token-set Overlap Coefficient: ``|A \u2229 B| / min(|A|, |B|)``.

    Returns ``1.0`` if both sets are empty (vacuously identical) and
    ``0.0`` if only one is empty (a non-empty query against an empty
    response is a degenerate match -- we reject it so the user gets a
    diagnostic instead of silently auto-corrected lyrics).
    """
    if not a and not b:
        return 1.0
    if not a or not b:
        return 0.0
    return len(a & b) / min(len(a), len(b))


def _is_genius_match(
    q_title: str, q_artist: str, r_title: str, r_artist: str,
) -> tuple[bool, str]:
    """``(is_match, diagnostic)`` -- verify Genius returned the song the user asked for.

    Returns ``(True, "")`` when title AND artist overlap (each >=) the
    threshold; otherwise a diagnostic that names both the query and the
    response so the user can fix their tags without re-running.

    Used by :meth:`GeniusClient.get` after the index-page filter.  Not
    requiring exact equality -- the Overlap Coefficient forgives the
    usual surface variants (``The Beatles`` vs ``Beatles``,
    ``feat. X``, ``(Remastered 2009)``, etc.) so a real match in a
    different release still goes through, but a wholly different
    popular song that share one common word with the query is rejected.
    """
    q_t = _genius_match_tokens(q_title)
    q_a = _genius_match_tokens(q_artist)
    r_t = _genius_match_tokens(r_title)
    r_a = _genius_match_tokens(r_artist)
    title_overlap = _overlap_coef(q_t, r_t)
    artist_overlap = _overlap_coef(q_a, r_a)
    if (
        title_overlap >= _GENIUS_MATCH_THRESHOLD
        and artist_overlap >= _GENIUS_MATCH_THRESHOLD
    ):
        return True, ""
    return False, (
        f"query '{q_title}' by '{q_artist}' != response "
        f"'{r_title}' by '{r_artist}' "
        f"(title={title_overlap:.2f}, artist={artist_overlap:.2f})"
    )


def _classify_genius_text(text: str) -> tuple[bool, str]:
    """``(is_index, why)`` -- detect Genius wiki/list pages and name the signal.

    Used by :meth:`GeniusClient.get` to reject obvious misclassifications
    so the lyrics chain can fall through to the next provider instead of
    writing a useless .lrc.  Two binary signals (no density thresholds)
    guard against false positives on legitimate rap/feature-heavy
    tracks:

    * **alphabet-navigation header** -- Genius table-of-contents /
      alphabetical indexes render as many adjacent single-character
      lines at the very top of the page body (``A\n|\nB\n|\nC\n|...``).
      No real song lyric body starts with this pattern.  ``isascii()
      and isalpha()`` is intentionally stricter than ``isalnum()`` so a
      poetic song that legitimately opens with one CJK ideograph per
      line cannot trip the threshold.
    * **long-body cap** -- a hard ceiling on LF count
      (``text.count("\\n")``).  Lyricsgenius returns LF- or
      CRLF-normalised text so this is reliable on both; it
      under-counts only degenerate CR-only files which lyricsgenius
      never produces.

    The ``why`` return value names which signal fired so the failure
    reason in :class:`LyricsFailure` is actionable in the GUI log
    panel (header mismatched tag fix; long body mismatched query fix).
    """
    # Signal 1: alphabet-navigation header.  Sample the first
    # ``_GENIUS_INDEX_HEAD_LEN`` non-blank lines; the ``islice`` cap
    # is mostly cosmetic -- ``splitlines()`` already walks the body --
    # but it makes the early-exit obvious to readers.
    head = list(islice(
        (l.strip() for l in text.splitlines() if l.strip()),
        _GENIUS_INDEX_HEAD_LEN,
    ))
    if len(head) >= 10:
        single_ascii_alpha = sum(
            1 for l in head if len(l) == 1 and l.isascii() and l.isalpha()
        )
        if single_ascii_alpha >= _GENIUS_INDEX_HEAD_MIN_SINGLE_CHARS:
            return True, "alphabet-navigation header detected"
    # Signal 2: long-body cap.  Wiki articles, transcripts, and book
    # chapters routinely exceed 1000 lines; even the longest songs in
    # any language + any section-marker style stay several hundred short.
    line_count = text.count("\n")
    if line_count > _GENIUS_INDEX_MAX_LINES:
        return True, f"body has {line_count} lines (cap={_GENIUS_INDEX_MAX_LINES})"
    return False, ""


class GeniusClient:
    """Adaptive wrapper around the ``lyricsgenius`` package.

    The package is optional -- if not installed or no token is supplied,
    ``get`` returns a :class:`LyricsFailure` immediately.
    """

    def __init__(self, access_token: Optional[str] = None) -> None:
        self.access_token = access_token
        self._genius: Optional["lyricsgenius.Genius"] = None  # type: ignore[name-defined]
        if access_token and lyricsgenius is not None:
            try:
                self._genius = lyricsgenius.Genius(
                    access_token,
                    timeout=15,
                    retries=2,
                    sleep_time=0.5,
                    remove_section_headers=True,
                    skip_non_songs=True,
                    excluded_terms=["(Remix)", "(Live)"],
                )
                self._genius.verbose = False
            except Exception as exc:  # pragma: no cover
                LOG.warning("Genius init failed: %s", exc)
                self._genius = None

    @property
    def enabled(self) -> bool:
        return self._genius is not None

    def get(self, *, artist: str, title: str) -> LyricsResult | LyricsFailure:
        if not self._genius:
            return LyricsFailure("genius", "no token / not installed")
        try:
            song = self._genius.search_song(title, artist)
        except Exception as exc:
            return LyricsFailure("genius", f"network error: {exc}")
        if song is None or not song.lyrics:
            return LyricsFailure("genius", "no match")
        text = song.lyrics.strip()
        if not text:
            return LyricsFailure("genius", "empty lyrics")
        # Reject obvious Genius wiki/list pages (``"List of..."`` entries
        # and similar) -- their ``song.lyrics`` body is an alphabet
        # navigation header followed by a name-registry dump, not
        # vocal lyrics.  Without this gate the fetcher would happily
        # write 2000+ lines of VTuber names into the user's .lrc.  See
        # :func:`_classify_genius_text` for the heuristic.
        is_index, why = _classify_genius_text(text)
        if is_index:
            return LyricsFailure(
                "genius", f"page looks like a Genius list/index ({why})",
            )
        # Auto-correct guard: even after the index-page filter, Genius
        # can return a totally different popular song whose title/artist
        # partially match the query (e.g. user types a typo and gets the
        # most-streamed result instead).  Token-set Overlap Coefficient
        # forgives surface variants (``The Beatles`` vs ``Beatles``,
        # ``feat. X``, ``(Remastered)``) but rejects genuinely different
        # songs.  See :func:`_is_genius_match` for the heuristic.
        primary = getattr(song, "primary_artist", None)
        album_field = getattr(song, "album", None)
        r_title = song.title or title
        r_artist = _extract_name(primary, default=artist)
        is_match, mismatch_why = _is_genius_match(
            title, artist, r_title, r_artist,
        )
        if not is_match:
            return LyricsFailure("genius", f"song mismatch: {mismatch_why}")
        if primary is not None and not isinstance(primary, (dict, str)):
            LOG.debug("Genius returned primary_artist of type %s", type(primary).__name__)
        return LyricsResult(
            provider="genius",
            title=r_title,
            artist=r_artist,
            album=_extract_name(album_field, default=""),
            length_seconds=0.0,
            synced_lines=[],
            plain_text=text,
        )


# ---------------------------------------------------------------------------
# Composite fetcher with fallback
# ---------------------------------------------------------------------------


class LyricsFetcher:
    """Source-aware fetcher.  ``source`` is one of:
        ``"auto"`` (LRCLIB then Genius, then audio if enabled),
        ``"lrclib"`` / ``"genius"`` (only that provider for the
        LRCLIB/Genius stage, but the audio fallback still applies
        when the analyzer is enabled),
        ``"audio"`` (local Whisper+Demucs only; requires the audio
        analyzer to be enabled via ``--use-audio-analysis`` or the
        GUI's 'Use audio analysis' checkbox).
    """

    def __init__(
        self,
        *,
        source: str = "auto",
        genius_token: Optional[str] = None,
        session: Optional[requests.Session] = None,
        audio_analyzer: Optional["object"] = None,
        cancel_event: Optional["threading.Event"] = None,
    ) -> None:
        """Construct a fetcher.

        ``audio_analyzer`` is an optional third-tier fallback (e.g.
        ``FasterWhisperAnalyzer``).  When provided, ``source="auto"`` chains
        ``lrclib -> genius -> audio_analyzer``.  ``cancel_event`` is checked
        between segments for prompt GUI cancellation.
        """
        self.source = source
        self.lrclib = LRCLIBClient(session=session)
        self.genius = GeniusClient(access_token=genius_token)
        self.audio_analyzer = audio_analyzer
        self.cancel_event = cancel_event

    # Substrings in the *filename* (case-insensitive, punctuation/whitespace
    # normalised) that mark a track as an instrumental / karaoke / backing-
    # track version.  We deliberately only short-circuit the LOCAL audio
    # analysis branch on a match -- LRCLIB + Genius still get a chance to
    # return the original song's lyrics, since ``"Song (Off Vocal).flac"``
    # is often a faithful cover of a real song that LRCLIB knows.
    # Filename check only; a title-tag counterpart is not implemented.
    _INSTRUMENTAL_FILENAME_PATTERNS: tuple[str, ...] = (
        # English patterns (existed since v1.1.0).
        "backing track",
        "inst version",
        "instrumental",
        "instrumental version",
        "karaoke",
        "minus one",
        "no vocal",
        "no vocals",
        "off vocal",        
        "vocal removed",
        "vocals removed",
        # No-separator / CamelCase variants. The CamelCase split in
        # _filename_blocks_audio (inserts a space at lowercase-uppercase
        # boundaries BEFORE lowercasing) already makes "SongOffVocal"
        # match the existing "off vocal" pattern. These dedicated
        # no-space entries are belt-and-suspenders for all-lowercase
        # filenames like "songoffvocal" where the CamelCase split
        # doesn't fire.
        "offvocal",
        "novocal",
        # Explicit hyphen variant. Redundant with "no vocal" after
        # the whitespace/hyphen normalisation, but kept per user
        # request for grep-ability.
        "no-vocal",
        # SEMANTIC NOTE: "acapella" / "акапелла" literally mean
        # "vocal-only, no instruments" -- the OPPOSITE of instrumental.
        # Whisper CAN transcribe these (there are vocals to transcribe).
        # Added per user request; remove these two entries if skipping
        # Whisper on a cappella files turns out to be undesirable.
        "acapella",
        "акапелла",
        # Russian equivalents of the English patterns above. The same
        # normalisation (CamelCase split + whitespace/punctuation
        # collapse) catches the usual variants.
        "инструментал",
        "караоке",
        "минусовка",
        "без вокала",
    )
    # Compiled once: a single anchored substring search is cheaper than 11
    # separate ``in`` checks on every audio file in a 300-track batch. The
    # outer ``(?:^|[\\s\\-_.])`` / ``(?:$|[\\s\\-_.])`` pair means a match
    # has to start AND end at a word/punctuation boundary -- ``"instrument"``
    # doesn't trigger ``"instrumental"``, and ``"tracklist"`` doesn't trigger
    # ``"backing track"``.
    _INSTRUMENTAL_FILENAME_RE = re.compile(
        r"(?:^|[\s\-_.])("
        + "|".join(re.escape(p) for p in _INSTRUMENTAL_FILENAME_PATTERNS)
        + r")(?:$|[\s\-_.])",
        re.IGNORECASE,
    )

    @staticmethod
    def _filename_blocks_audio(audio: AudioFile) -> bool:
        """True if ``audio.path`` looks like an instrumental/karaoke version.

        Normalises the stem in TWO steps so the usual variants all match
        the same pattern:

        1. **CamelCase split** -- inserts a space at every
           lowercase-uppercase boundary (``offVocal`` -> ``off Vocal``,
           ``SongOffVocal`` -> ``Song Off Vocal``). This MUST run before
           lowercasing, because lowercasing first would lose the
           boundary positions.
        2. **Whitespace / punctuation collapse + lowercase** -- collapses
           any run of whitespace / ``-`` / ``_`` / ``.`` / ``\\`` to a
           single space, then lowercases. So ``"Song-Off-Vocal.flac"``,
           ``"song_off_vocal.flac"`` and ``"song off vocal.flac"`` all
           normalise to ``"song off vocal"`` and match the existing
           ``"off vocal"`` pattern.

        Used to short-circuit the audio-analysis branch in :meth:`fetch`;
        the LRCLIB / Genius branches are untouched so a karaoke file
        whose original has real lyrics still gets an LRC.
        """
        # Unicode-aware CamelCase split: matches at every
        # lowercase-then-uppercase boundary for BOTH ASCII and
        # Cyrillic. The Cyrillic ranges are U+0430–U+044F (lowercase)
        # and U+0410–U+042F (uppercase), which covers standard
        # Russian filenames like ``ПесняИнструментал``. Without
        # these ranges, the Cyrillic boundary is invisible to the
        # ASCII-only ``[a-z][A-Z]`` pattern, and ``ПесняИнструментал``
        # never gets split -- so the new ``инструментал`` pattern
        # can't match (the ASCII-only ``[\s\-_.]`` boundary in the
        # compiled regex would see a Cyrillic letter, not a boundary,
        # at the position between ``я`` and ``и``).
        stem_with_camelcase_spaces = re.sub(
            r"([a-z\u0430-\u044f])([A-Z\u0410-\u042f])", r"\1 \2",
            audio.path.stem,
        )
        name = re.sub(
            r"[\s\-_.]+", " ", stem_with_camelcase_spaces.lower()
        ).strip()
        return bool(LyricsFetcher._INSTRUMENTAL_FILENAME_RE.search(name))

    def fetch(self, audio: AudioFile) -> LyricsResult | LyricsFailure:
        # Instrumental short-circuit (filename only) lives in the ``audio``
        # branch below.  LRCLIB + Genius are deliberately NOT gated -- a
        # karaoke file whose original song has real lyrics still gets an LRC.

        if self.source == "auto":
            order = ["lrclib", "genius"]
            if self.audio_analyzer is not None:
                order.append("audio")
        elif self.source in ("lrclib", "genius"):
            order = [self.source] + (
                ["audio"] if self.audio_analyzer is not None else []
            )
        elif self.source == "audio":
            # Source='audio' is the local-only chain: a missing or
            # disabled audio analyzer (CLI user forgot
            # ``--use-audio-analysis``, OR faster-whisper failed to
            # construct / isn't installed) would otherwise leave the
            # order list empty and trip the ``assert last is not None``
            # below -- crashing the worker mid-batch. Short-circuit to
            # a clean LyricsFailure so the run finishes normally with
            # a ``missing`` outcome (the per-file line in the log
            # panel / summary explains why).
            if self.audio_analyzer is None or not self.audio_analyzer.enabled:
                return LyricsFailure(
                    "audio",
                    "source='audio' requires --use-audio-analysis "
                    "(audio analyzer unavailable)",
                )
            order = ["audio"]
        else:
            return LyricsFailure("config", f"unknown source {self.source!r}")

        last: LyricsResult | LyricsFailure | None = None
        for provider in order:
            if provider == "lrclib":
                r = self.lrclib.get(
                    artist=audio.artist,
                    title=audio.title,
                    album=audio.album,
                    duration=audio.duration,
                )
            elif provider == "genius":
                if not self.genius.enabled:
                    last = LyricsFailure("genius", "no token / not installed")
                    continue
                r = self.genius.get(artist=audio.artist, title=audio.title)
            elif provider == "audio":
                if self.audio_analyzer is None or not self.audio_analyzer.enabled:
                    last = LyricsFailure(
                        self.audio_analyzer.name if self.audio_analyzer else "audio",
                        "audio analyzer disabled / not installed",
                    )
                    continue
                # Filename-based short-circuit: never run Whisper on a
                # track that the user clearly named as instrumental /
                # karaoke / off-vocal. The LRCLIB + Genius branches
                # above are NOT gated by this check on purpose -- those
                # providers index the original song and often return
                # usable lyrics even when the local file is a cover /
                # backing track.
                if self._filename_blocks_audio(audio):
                    last = LyricsFailure(
                        "audio",
                        "filename matches karaoke/instrumental pattern; "
                        "audio analysis skipped",
                    )
                    LOG.info(
                        "Skipping audio analysis for %s: filename matches "
                        "karaoke/instrumental pattern",
                        audio.path.name,
                    )
                    continue
                r = self.audio_analyzer.get(audio, stop_event=self.cancel_event)
            else:
                continue  # pragma: no cover

            if isinstance(r, LyricsResult):
                # Accept synced lines OR a plain text body long enough to be useful.
                if r.is_synced or len(r.plain_text) >= 8:
                    return r
                # Provider returned a tiny plain snippet -- try next.
            last = r

        assert last is not None  # noqa: S101 - order is always non-empty
        return last


__all__: Iterable[str] = (
    "ENV_GENIUS_TOKEN",
    "GeniusClient",
    "LRCLIBClient",
    "LyricsFailure",
    "LyricsFetcher",
    "LyricsResult",
    "WHISPER_DEMUCS_PROVIDER_MARKER",
    "WHISPER_PROVIDER_MARKER",
    "WHISPER_PROVIDER_NAME",
)
