"""Lyrics fetchers with a chained fallback strategy.

Defaults to LRCLIB first (returns synced lyrics natively -> best LRC output)
and falls back to Genius (huge database, unsynced plain text).  Either
provider can be selected exclusively via ``LyricsFetcher(source="...")``.

Network errors and empty results are tolerated; both providers log their
decisions so the caller can surface a "skipped: <reason>" message.
"""

from __future__ import annotations

import logging
import threading
from dataclasses import dataclass, field
from typing import Iterable, Optional

import re
import requests

try:
    import lyricsgenius  # type: ignore
except ImportError:  # pragma: no cover - optional at runtime
    lyricsgenius = None  # type: ignore[assignment]

from .audio import AudioFile
from .lrc import LRCDocument, split_synced_text

LOG = logging.getLogger(__name__)

LRCLIB_BASE = "https://lrclib.net/api"
LRCLIB_TIMEOUT = 15
LRCLIB_USER_AGENT = "LyricsFAG/0.1 (https://github.com/local/lyricsfag)"

# Genius API access token (free at https://genius.com/api-clients).  When
# omitted, the library silently skips Genius and reports "no token".
ENV_GENIUS_TOKEN = "GENIUS_ACCESS_TOKEN"

# Human-readable marker prepended to ``diagnostic_lines`` whenever the
# lyrics came from local ``faster-whisper`` transcription.  The square-
# bracket-hash form matches the existing ``[# ...]`` line convention so
# :func:`split_synced_text` and :func:`header_lines` skip it (they
# neither match the ``[mm:ss]`` timestamp gate nor the
# ``[a-zA-Z]+:..]`` ID3 header regex).  See
# :func:`_format_diagnostics` for the parser-safety contract.
WHISPER_PROVIDER_MARKER = "[# Generated Lyrics with Whisper]"
# Variant emitted when Whisper ran on vocals pre-isolated by Demucs; the
# .lrc reader sees ONE human-readable line, so we encode the pipeline
# distinction in the label rather than dumping a second diagnostic.
WHISPER_DEMUCS_PROVIDER_MARKER = "[# Generated Lyrics with Demucs + Whisper]"

# Provider name emitted by :class:`FasterWhisperAnalyzer`.  Centralised
# here so the GUI / CLI / LRC writers don't drift if the analyzer is
# ever renamed -- one constant change keeps the marker logic in sync.
WHISPER_PROVIDER_NAME = "whisper"


def _extract_name(field_val, default: str = "") -> str:
    """Coerce ``Song.primary_artist`` / ``Song.album`` into a plain name.

    ``lyricsgenius >= 3`` stores nested Genius entities (``primary_artist``,
    ``album``, etc.) as raw dicts carved straight from the JSON API response --
    not as ``Artist``/``Album`` instances.  Older fixtures, mocked responses, or
    future versions may return object instances with a ``.name`` attribute.
    This helper accepts both shapes (and ``None``/``str``) and returns the
    human-readable name.
    """
    if not field_val:
        return default
    if isinstance(field_val, str):
        return field_val or default
    if isinstance(field_val, dict):
        name = field_val.get("name")
        return name if isinstance(name, str) and name else default
    # Object-like (custom class with a ``name`` attribute)
    name = getattr(field_val, "name", None)
    if isinstance(name, str) and name:
        return name
    return default


def _format_diagnostics(result: "LyricsResult") -> list[str]:
    """Render a ``LyricsResult``'s provenance as a single ``[# ...]`` line.

    Output format::

        [# generated by <provider>; <sorted-key>=<value>; ...]

    When ``raw_extras`` is empty we still emit a provider-only line so the
    LRC carries a consistent provenance marker for every successful result
    (LRCLIB / Genius / heuristic / whisper / vad-preflight).

    Non-scalar extras (``None``, ``list``, ``dict``, ``set``, ``tuple``,
    ``Decimal``, ``UUID``, ``Path``, ``bytes``, ``datetime``, ...) and scalar
    values whose string form is empty or contains ``;`` or ``]`` are dropped
    with a ``LOG.warning``.  The format has no quoting, so a stray separator
    would corrupt the single ``[# ...]`` line and break the parser-safety
    guarantee below.

    The ``provider`` name is filtered the same way: empty, or ``;``/``]``,
    cause the entire diagnostic line to be suppressed (without a parsable
    provider there's nothing safe to record).

    Provider authors should keep ``raw_extras`` keys lowercase so the
    sorted-by-key iteration produces stable diffs across runs.    Conventional LRC parsers ``split_synced_text`` and ``header_lines``
    already skip ``[# ...]`` lines (their regexes demand ``[mm:ss]``
    timestamps or ``[a-zA-Z]+:..]`` headers respectively), so the
    diagnostic never bleeds into the visible lyric stream.
    """
    provider = result.provider or ""
    if not provider or ";" in provider or "]" in provider:
        LOG.warning(
            "diagnostic: dropping entire line; empty or unsafe provider name %r",
            provider,
        )
        return []
    # Whisper diagnostics are intentionally curtailed here: the human-
    # readable ``WHISPER_PROVIDER_MARKER`` (or its ``Demucs +`` variant)
    # already tells the reader where the synth lyrics came from, and the
    # verbose ``compute_type``/``device``/``duration``/... line is too
    # noisy for a file the user opens in their music player. ``raw_extras``
    # itself stays populated so non-LRC consumers (logger, GUI status)
    # keep the underlying detail. Other providers (LRCLIB, Genius,
    # heuristic, vad-preflight) keep the original verbose line because
    # they have no equivalent friendly marker.
    if provider == WHISPER_PROVIDER_NAME:
        return []
    extras: list[str] = [] 
    for key, value in sorted(result.raw_extras.items()):
        if not isinstance(value, (str, int, float, bool)):
            LOG.warning(
                "diagnostic: dropping non-scalar extra %s=%r",
                key, value,
            )
            continue
        rendered = str(value)
        if not rendered or ";" in rendered or "]" in rendered:
            LOG.warning(
                "diagnostic: dropping empty or unsafe extra %s=%r",
                key, value,
            )
            continue
        extras.append(f"{key}={rendered}")
    if extras:
        return [f"[# generated by {provider}; " + "; ".join(extras) + "]"]
    return [f"[# generated by {provider}]"]


@dataclass
class LyricsResult:
    """Successful response from a provider.

    ``synced_lines`` is the list of (timestamp_str, text) pairs; empty if the
    result is unsynced (e.g. from Genius).  ``source`` records which provider
    produced the data for later logging.
    """

    provider: str
    title: str
    artist: str
    album: str = ""
    length_seconds: float = 0.0
    synced_lines: list[tuple[str, str]] = field(default_factory=list)
    plain_text: str = ""
    instrumental: bool = False
    raw_extras: dict = field(default_factory=dict)

    @property
    def is_synced(self) -> bool:
        return bool(self.synced_lines)

    def to_document(self) -> LRCDocument:
        """Convert this result into an :class:`LRCDocument` ready for writing."""
        diagnostics: list[str] = _format_diagnostics(self)
        # When this result came from local faster-whisper transcription,
        # prepend a stable, human-readable marker so anyone reading the
        # .lrc file can tell at a glance that the lyrics are synthetic
        # and may need a manual pass for accuracy.  When the run also
        # went through Demucs vocal isolation, the label spells that out
        # so the reader knows the pipeline ordered differently than a
        # plain Whisper pass.  ``vocal_isolation`` is set by
        # :class:`FasterWhisperAnalyzer` to ``"demucs"`` or ``"raw"``;
        # any future value (or a missing key) falls back to the plain
        # Whisper marker rather than guessing.  The marker is the only
        # diagnostic line for Whisper -- ``_format_diagnostics`` no
        # longer emits the structured ``[# generated by whisper; ...]``
        # line, which kept ``compute_type``/``device``/``duration``/... in
        # the user's .lrc file but added nothing actionable for them.
        if self.provider == WHISPER_PROVIDER_NAME:
            if self.raw_extras.get("vocal_isolation") == "demucs":
                diagnostics.insert(0, WHISPER_DEMUCS_PROVIDER_MARKER)
            else:
                diagnostics.insert(0, WHISPER_PROVIDER_MARKER)
        doc = LRCDocument(
            title=self.title,
            artist=self.artist,
            album=self.album,
            length_seconds=self.length_seconds,
            diagnostic_lines=diagnostics,
        )
        if self.synced_lines:
            doc.lines = list(self.synced_lines)
        elif self.plain_text:
            for line in self.plain_text.splitlines():
                doc.add("", line)
        return doc


@dataclass
class LyricsFailure:
    provider: str
    reason: str


# ---------------------------------------------------------------------------
# LRCLIB client
# ---------------------------------------------------------------------------


class LRCLIBClient:
    """Thin wrapper over the public LRCLIB.net API."""

    def __init__(self, session: Optional[requests.Session] = None) -> None:
        self.session = session or requests.Session()
        self.session.headers.setdefault("User-Agent", LRCLIB_USER_AGENT)

    def get(
        self,
        *,
        artist: str,
        title: str,
        album: str = "",
        duration: float = 0.0,
    ) -> LyricsResult | LyricsFailure:
        url = f"{LRCLIB_BASE}/get"
        params = {
            "artist_name": artist,
            "track_name": title,
        }
        if album:
            params["album_name"] = album
        if duration > 0:
            params["duration"] = int(round(duration))

        try:
            resp = self.session.get(url, params=params, timeout=LRCLIB_TIMEOUT)
        except requests.RequestException as exc:
            return LyricsFailure("lrclib", f"network error: {exc}")

        if resp.status_code == 404:
            return LyricsFailure("lrclib", "no match")
        if resp.status_code == 429:
            return LyricsFailure("lrclib", "rate limited")
        if resp.status_code >= 500:
            return LyricsFailure("lrclib", f"server error {resp.status_code}")
        if not resp.ok:
            return LyricsFailure("lrclib", f"HTTP {resp.status_code}")

        try:
            data = resp.json()
        except ValueError as exc:
            return LyricsFailure("lrclib", f"bad json: {exc}")
        if not isinstance(data, dict):
            return LyricsFailure("lrclib", "unexpected payload shape")

        synced = (data.get("syncedLyrics") or "").strip()
        plain = (data.get("plainLyrics") or "").strip()

        if not synced and not plain:
            return LyricsFailure("lrclib", "empty payload")

        return LyricsResult(
            provider="lrclib",
            title=data.get("trackName") or title,
            artist=data.get("artistName") or artist,
            album=data.get("albumName") or album,
            length_seconds=float(data.get("duration") or duration or 0),
            synced_lines=split_synced_text(synced) if synced else [],
            plain_text=plain if not synced else "",
            instrumental=plain.lower() in {"[instrumental]", "instrumental"},
            # Filter empty values out of ``raw_extras`` so the defensive
            # ``_format_diagnostics`` doesn't fire its
            # ``diagnostic: dropping empty or unsafe extra`` WARNING for
            # LRCLIB responses that lack the optional ``url`` field
            # (lrclib.net doesn't always fill it in -- without this gate
            # every such hit would warn once per file).  Both ``id`` and
            # ``lrclib_url`` are filtered the same way so the syntax
            # stays uniform -- a missing ``id`` is rare but the
            # comprehension handles both cases with no extra cost.
            raw_extras={
                k: v for k, v in (
                    ("id", data.get("id")),
                    ("lrclib_url", data.get("url") or ""),
                )
                if v
            },
        )


# ---------------------------------------------------------------------------
# Genius client
# ---------------------------------------------------------------------------


class GeniusClient:
    """Adaptive wrapper around the ``lyricsgenius`` package.

    The package is optional -- if not installed or no token is supplied,
    ``get`` returns a :class:`LyricsFailure` immediately.
    """

    def __init__(self, access_token: Optional[str] = None) -> None:
        self.access_token = access_token
        self._genius: Optional["lyricsgenius.Genius"] = None  # type: ignore[name-defined]
        if access_token and lyricsgenius is not None:
            try:
                self._genius = lyricsgenius.Genius(
                    access_token,
                    timeout=15,
                    retries=2,
                    sleep_time=0.5,
                    remove_section_headers=True,
                    skip_non_songs=True,
                    excluded_terms=["(Remix)", "(Live)"],
                )
                self._genius.verbose = False
            except Exception as exc:  # pragma: no cover
                LOG.warning("Genius init failed: %s", exc)
                self._genius = None

    @property
    def enabled(self) -> bool:
        return self._genius is not None

    def get(self, *, artist: str, title: str) -> LyricsResult | LyricsFailure:
        if not self._genius:
            return LyricsFailure("genius", "no token / not installed")
        try:
            song = self._genius.search_song(title, artist)
        except Exception as exc:
            return LyricsFailure("genius", f"network error: {exc}")
        if song is None or not song.lyrics:
            return LyricsFailure("genius", "no match")
        text = song.lyrics.strip()
        if not text:
            return LyricsFailure("genius", "empty lyrics")
        primary = getattr(song, "primary_artist", None)
        album_field = getattr(song, "album", None)
        if primary is not None and not isinstance(primary, (dict, str)):
            LOG.debug("Genius returned primary_artist of type %s", type(primary).__name__)
        return LyricsResult(
            provider="genius",
            title=song.title or title,
            artist=_extract_name(primary, default=artist),
            album=_extract_name(album_field, default=""),
            length_seconds=0.0,
            synced_lines=[],
            plain_text=text,
        )


# ---------------------------------------------------------------------------
# Composite fetcher with fallback
# ---------------------------------------------------------------------------


class LyricsFetcher:
    """Source-aware fetcher.  ``source`` is one of:
        ``"auto"`` (LRCLIB then Genius, then audio if enabled),
        ``"lrclib"`` / ``"genius"`` (only that provider for the
        LRCLIB/Genius stage, but the audio fallback still applies
        when the analyzer is enabled),
        ``"audio"`` (local Whisper+Demucs only; requires the audio
        analyzer to be enabled via ``--use-audio-analysis`` or the
        GUI's 'Use audio analysis' checkbox).
    """

    def __init__(
        self,
        *,
        source: str = "auto",
        genius_token: Optional[str] = None,
        session: Optional[requests.Session] = None,
        audio_analyzer: Optional["object"] = None,
        cancel_event: Optional["threading.Event"] = None,
    ) -> None:
        """Construct a fetcher.

        ``audio_analyzer`` is an optional third-tier fallback (e.g.
        ``FasterWhisperAnalyzer``).  When provided, ``source="auto"`` chains
        ``lrclib -> genius -> audio_analyzer``.  ``cancel_event`` is checked
        between segments for prompt GUI cancellation.
        """
        self.source = source
        self.lrclib = LRCLIBClient(session=session)
        self.genius = GeniusClient(access_token=genius_token)
        self.audio_analyzer = audio_analyzer
        self.cancel_event = cancel_event

    @staticmethod
    def _looks_instrumental(audio: AudioFile) -> bool:
        t = (audio.title or "").lower()
        return "instrumental" in t or "(karaoke)" in t

    # Substrings in the *filename* (case-insensitive, punctuation/whitespace
    # normalised) that mark a track as an instrumental / karaoke / backing-
    # track version.  We deliberately only short-circuit the LOCAL audio
    # analysis branch on a match -- LRCLIB + Genius still get a chance to
    # return the original song's lyrics, since ``"Song (Off Vocal).flac"``
    # is often a faithful cover of a real song that LRCLIB knows.
    # Note this is a filename check, not a title check (the title-based
    # short-circuit in :meth:`_looks_instrumental` is unrelated and stays).
    _INSTRUMENTAL_FILENAME_PATTERNS: tuple[str, ...] = (
        "backing track",
        "inst version",
        "instrumental",
        "instrumental version",
        "karaoke",
        "minus one",
        "no vocal",
        "no vocals",
        "off vocal",
        "vocal removed",
        "vocals removed",
    )
    # Compiled once: a single anchored substring search is cheaper than 11
    # separate ``in`` checks on every audio file in a 300-track batch. The
    # outer ``(?:^|[\\s\\-_.])`` / ``(?:$|[\\s\\-_.])`` pair means a match
    # has to start AND end at a word/punctuation boundary -- ``"instrument"``
    # doesn't trigger ``"instrumental"``, and ``"tracklist"`` doesn't trigger
    # ``"backing track"``.
    _INSTRUMENTAL_FILENAME_RE = re.compile(
        r"(?:^|[\s\-_.])("
        + "|".join(re.escape(p) for p in _INSTRUMENTAL_FILENAME_PATTERNS)
        + r")(?:$|[\s\-_.])",
        re.IGNORECASE,
    )

    @staticmethod
    def _filename_blocks_audio(audio: AudioFile) -> bool:
        """True if ``audio.path`` looks like an instrumental/karaoke version.

        Normalises the stem (lowercase, collapses ``-`` / ``_`` / ``.`` /
        ``\\`` and runs of whitespace into a single space) so
        ``"Song-Off-Vocal.flac"``, ``"song_off_vocal.flac"`` and
        ``"song off vocal.flac"`` all match the same pattern. Used to
        short-circuit the audio-analysis branch in :meth:`fetch`; the
        LRCLIB / Genius branches are untouched so a karaoke file whose
        original has real lyrics still gets an LRC.
        """
        name = re.sub(r"[\s\-_.]+", " ", audio.path.stem.lower()).strip()
        return bool(LyricsFetcher._INSTRUMENTAL_FILENAME_RE.search(name))

    def fetch(self, audio: AudioFile) -> LyricsResult | LyricsFailure:
        if self._looks_instrumental(audio):
            return LyricsResult(
                provider="heuristic",
                title=audio.title,
                artist=audio.artist,
                album=audio.album,
                length_seconds=audio.duration,
                plain_text="[Instrumental]",
                instrumental=True,
            )

        if self.source == "auto":
            order = ["lrclib", "genius"]
            if self.audio_analyzer is not None:
                order.append("audio")
        elif self.source in ("lrclib", "genius"):
            order = [self.source] + (
                ["audio"] if self.audio_analyzer is not None else []
            )
        elif self.source == "audio":
            # Source='audio' is the local-only chain: a missing or
            # disabled audio analyzer (CLI user forgot
            # ``--use-audio-analysis``, OR faster-whisper failed to
            # construct / isn't installed) would otherwise leave the
            # order list empty and trip the ``assert last is not None``
            # below -- crashing the worker mid-batch. Short-circuit to
            # a clean LyricsFailure so the run finishes normally with
            # a ``missing`` outcome (the per-file line in the log
            # panel / summary explains why).
            if self.audio_analyzer is None or not self.audio_analyzer.enabled:
                return LyricsFailure(
                    "audio",
                    "source='audio' requires --use-audio-analysis "
                    "(audio analyzer unavailable)",
                )
            order = ["audio"]
        else:
            return LyricsFailure("config", f"unknown source {self.source!r}")

        last: LyricsResult | LyricsFailure | None = None
        for provider in order:
            if provider == "lrclib":
                r = self.lrclib.get(
                    artist=audio.artist,
                    title=audio.title,
                    album=audio.album,
                    duration=audio.duration,
                )
            elif provider == "genius":
                if not self.genius.enabled:
                    last = LyricsFailure("genius", "no token / not installed")
                    continue
                r = self.genius.get(artist=audio.artist, title=audio.title)
            elif provider == "audio":
                if self.audio_analyzer is None or not self.audio_analyzer.enabled:
                    last = LyricsFailure(
                        self.audio_analyzer.name if self.audio_analyzer else "audio",
                        "audio analyzer disabled / not installed",
                    )
                    continue
                # Filename-based short-circuit: never run Whisper on a
                # track that the user clearly named as instrumental /
                # karaoke / off-vocal. The LRCLIB + Genius branches
                # above are NOT gated by this check on purpose -- those
                # providers index the original song and often return
                # usable lyrics even when the local file is a cover /
                # backing track.
                if self._filename_blocks_audio(audio):
                    last = LyricsFailure(
                        "audio",
                        "filename matches karaoke/instrumental pattern; "
                        "audio analysis skipped",
                    )
                    LOG.info(
                        "Skipping audio analysis for %s: filename matches "
                        "karaoke/instrumental pattern",
                        audio.path.name,
                    )
                    continue
                r = self.audio_analyzer.get(audio, stop_event=self.cancel_event)
            else:
                continue  # pragma: no cover

            if isinstance(r, LyricsResult):
                # Accept synced lines OR a plain text body long enough to be useful.
                if r.is_synced or len(r.plain_text) >= 8:
                    return r
                # Provider returned a tiny plain snippet -- try next.
            last = r

        assert last is not None  # noqa: S101 - order is always non-empty
        return last


__all__: Iterable[str] = (
    "ENV_GENIUS_TOKEN",
    "GeniusClient",
    "LRCLIBClient",
    "LyricsFailure",
    "LyricsFetcher",
    "LyricsResult",
    "WHISPER_DEMUCS_PROVIDER_MARKER",
    "WHISPER_PROVIDER_MARKER",
    "WHISPER_PROVIDER_NAME",
)
