"""Embed plain-text lyrics into an audio file's native lyrics tag.

Driving API:
    - :class:`EmbedResult`: outcome of a single ``embed_lyrics()`` call.
    - :func:`embed_lyrics`: the one and only entry point -- dispatches on
      the ``mutagen.File()``-inferred class and writes the format's
      conventional lyrics tag.

The audio file's format is detected by :func:`mutagen.File` so dispatch
goes through ``isinstance`` on the concrete ``mutagen.*``
class -- extension-based dispatch is fragile (e.g. ``mutagen.File``
correctly identifies a ``.ogg`` that holds Opus + the speaker still
gets ``LYRICS`` written into the Vorbis comment).

Format coverage (all opt-in via ``--embed-in-tags`` / GUI checkbox:

================  ============================  =====================
Format            Tag key written               Read by (most)
================  ============================  =====================
MP3 (ID3v2)       ``USLT`` (UTF-8, lang='eng')  foobar, AIMP, iTunes,
                                                 MusicBee, WMP, Vanilla
FLAC / OGG / OPUS Vorbis ``LYRICS`` key         foobar, AIMP, MusicBee,
                                                 Vanilla, Musicolet
MP4 / M4A         atom ``\\xa9lyr``              iTunes, MusicBee (with
                                                 MP4 plugin), JRiver,
                                                 foobar2000 (mp4 input)
WMA (ASF)         descriptor ``WM/Lyrics``      Windows Media Player,
                                                 MusicBee, foobar2000
WavPack (WV)      APEv2 ``LYRICS`` key          foobar, AIMP, MusicBee
APE (.ape)        APEv2 ``LYRICS`` key          foobar, AIMP, MusicBee
WAV               -- no standard lyrics tag --  (skipped + log-warned)
TAK               -- no standard lyrics tag --  (skipped + log-warned)
AAC (raw ADTS)    -- no standard lyrics tag --  (skipped + log-warned;
                                                 mutagen returns the
                                                 bitstream container but
                                                 has no tag writer)
================  ============================  =====================

Force semantics
---------------
``force=False`` (the ``--no-force`` surface) means *do not touch
existing things*, identical to the policy applied to the sidecar
``.lrc``: a pre-existing ``USLT`` / ``LYRICS`` / ``\\xa9lyr`` /
``WM/Lyrics`` frame is left untouched and ``EmbedResult.status`` is
``"skipped"`` so the per-file log line carries the right suffix
(``[tags=skipped (existing)]``).

``force=True`` overwrites in-place -- ID3 uses
``delall('USLT')`` + ``add`` so we don't leave a multi-language /
multi-desc USLT ghost-frame from the previous tagging run; Vorbis /
MP4 / ASF / APE key replacement is just ``dict[k] = [text]`` /
``dict[k] = text`` and fully replaces the entry.

Atomicity
---------
:func:`mutagen.File.save` is not strictly atomic at the byte level
(id3 padding tweaks may rewrite part of the file in place; an
exhausted padding slot triggers a full ``tempfile`` rewrite). This is
the standard tradeoff for tag writing; ``lyricsfag_lib.lrc.write_lrc``
gets atomicity for free via a sibling ``.tmp`` + ``replace``, but the
audio file as a whole cannot be moved that cleanly. We accept the
shared risk -- a power loss mid-``save`` could in theory leave a
zero-byte audio file. In practice: every modern mutagen version
writes to a tempfile when a full rewrite is needed and the cache of
unfinished files is well-tested.

Diagnostic data
---------------
The plain lyrics text passed in *must* have already been
extracted/sanitised: see :func:`lyricsfag_lib.lrc.extract_plain_lyrics`.
Headers (e.g. ``[ti:..]``) and producer diagnostics (e.g.
``[# generated by whisper]``) are NOT embedded -- the audio tag
holds only the actual lyric content.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import mutagen
from mutagen.asf import ASF
from mutagen.flac import FLAC
from mutagen.id3 import USLT
from mutagen.monkeysaudio import MonkeysAudio
from mutagen.mp3 import MP3
from mutagen.mp4 import MP4
from mutagen.oggvorbis import OggVorbis
from mutagen.oggopus import OggOpus
from mutagen.wavpack import WavPack

LOG = logging.getLogger(__name__)


# -----------------------------------------------------------------------
# Result dataclass
# -----------------------------------------------------------------------


@dataclass
class EmbedResult:
    """Outcome of a single :func:`embed_lyrics` call.

    Attributes
    ----------
    supported
        ``True`` when the format is recognised and mutable, ``False`` when
        the format has no standard lyrics tag (e.g. ``WAVE`` or ``TAK``).
    format
        ``mutagen`` class name, e.g. ``"MP3"``, ``"FLAC"``, ``"OggVorbis"``,
        ``"MP4"``, ``"ASF"``, ``"WavPack"``, ``"MonkeysAudio"``,
        ``"WAVE"``, ``"TAK"``. ``""`` if the file couldn't even be opened.
    tag_name
        Concrete tag key written, e.g. ``"USLT"``, ``"LYRICS"``,
        ``"\\xa9lyr"``, ``"WM/Lyrics"``. ``""`` on unsupported formats.
    status
        One of:

        * ``""``              -- did not attempt (empty plain text)
        * ``"embedded"``      -- tag was written
        * ``"skipped"``       -- format supported but tag already present
                                  and ``force=False`` was honoured
        * ``"unsupported"``   -- format has no standard lyrics tag
                                  (e.g. WAV / TAK)
        * ``"error"``         -- format supported but ``mutagen.save``
                                  raised (file permissions, disk-full,
                                  corrupt input, etc.)
    error
        Human-readable diagnostic for ``status="error"`` /
        ``status="unsupported"``. Empty otherwise.
    """

    supported: bool
    format: str = ""
    tag_name: str = ""
    status: str = ""
    error: str = ""

    @property
    def wrote(self) -> bool:
        """``True`` iff a tag genuinely landed on disk this call."""
        return self.status == "embedded"


# -----------------------------------------------------------------------
# Public dispatch
# -----------------------------------------------------------------------


def embed_lyrics(audio_path: Path, plain_text: str, *, force: bool = True) -> EmbedResult:
    """Write ``plain_text`` into ``audio_path``'s native lyrics tag.

    Parameters
    ----------
    audio_path
        Existing audio file we want to tag. The audio data is not
        re-encoded.
    plain_text
        Lyrics body in plain text (timestamps already stripped). See
        :func:`lyricsfag_lib.lrc.extract_plain_lyrics` for the canonical
        sanitiser used by :func:`lyricsfag.process_one`.

        An empty ``plain_text`` short-circuits to
        ``EmbedResult(status="unsupported", error="empty plain text")``
        -- we never write an empty lyrics frame, which is the ISBN of
        every half-finished tagging pass.
    force
        When ``False``, an existing lyrics tag of any flavour is left
        untouched and ``status="skipped"``. When ``True``, any
        pre-existing frame is fully replaced.

    Returns
    -------
    :class:`EmbedResult` describing what was (or wasn't) done. Never
    raises -- unrecognised / unreadable formats bubble up as
    ``status="error"`` / ``"unsupported"`` so the batch driver can
    keep going.
    """
    if not plain_text or not plain_text.strip():
        return EmbedResult(
            supported=False, format="", tag_name="",
            status="unsupported", error="empty plain text",
        )
    try:
        mf = mutagen.File(str(audio_path))
    except Exception as exc:
        # Unreadable / corrupt / permission-denied -> not our bug;
        # we surface it but don't crash the worker. ``LOG.debug`` keeps
        # it out of the default info log; the
        # ``process_one`` outcome's ``tags_error`` field still surfaces
        # the message to the GUI log panel / CLI summary.
        LOG.debug("mutagen.File failed for %s: %s", audio_path, exc)
        return EmbedResult(
            supported=False, format="?", tag_name="",
            status="error", error=f"mutagen.File: {exc}",
        )
    if mf is None:
        return EmbedResult(
            supported=False, format="?", tag_name="",
            status="error", error="mutagen.File returned None (unrecognised container)",
        )

    # Concrete-class dispatch.  Ordered roughly by popularity so the
    # common case resolves with a single isinstance() check.
    if isinstance(mf, MP3):
        return _embed_id3(mf, audio_path, plain_text, force)
    if isinstance(mf, FLAC) or isinstance(mf, OggVorbis) or isinstance(mf, OggOpus):
        return _embed_vorbis_comment(mf, audio_path, plain_text, force)
    if isinstance(mf, MP4):
        return _embed_mp4(mf, audio_path, plain_text, force)
    if isinstance(mf, ASF):
        return _embed_asf(mf, audio_path, plain_text, force)
    # WavPack + MonkeysAudio (.ape) both carry APEv2 tags.
    if isinstance(mf, WavPack) or isinstance(mf, MonkeysAudio):
        return _embed_apev2(mf, audio_path, plain_text, force)

    # WAV and TAK land here: no standard lyrics tag in mutagen for
    # either.  Returned as ``supported=False`` so the per-file log line
    # picks up a ``tags=skipped (no standard tag)`` suffix instead of
    # an error -- a worker crash would NOT help here.
    fmt = type(mf).__name__
    return EmbedResult(
        supported=False, format=fmt, tag_name="",
        status="unsupported",
        error=f"no standard lyrics tag for {fmt}",
    )


# -----------------------------------------------------------------------
# Per-format implementations
# -----------------------------------------------------------------------


def _embed_id3(
    mf: MP3, audio_path: Path, plain_text: str, force: bool,
) -> EmbedResult:
    """Write ``plain_text`` into a MP3 ID3v2 ``USLT`` frame.

    Uses ``encoding=3`` (UTF-8) so Cyrillic / CJK / emoji round-trip
    cleanly through every modern player. ``lang='eng'`` (ISO 639-2) is
    used as the language placeholder: every reader we tested renders
    the lyrics regardless of the lang code (it's purely a hint for
    filtering UI), and 'eng' matches what the bulk of the world's
    taggers default to.
    """
    # MP3 reading can return a file with no ID3 header at all (raw
    # MPEG stream) -> ``mf.tags is None``.  ``add_tags()`` constructs
    # a fresh ID3v2 header on save.  Idempotent: no-op when ``tags``
    # already exists.
    if mf.tags is None:
        mf.add_tags()
    existing = mf.tags.getall("USLT")
    if existing and not force:
        return EmbedResult(
            supported=True, format="MP3", tag_name="USLT",
            status="skipped",
            error="USLT already present; pass --force to overwrite",
        )
    # Multi-language / multi-desc ghost-frames from a previous
    # tagger survive a naive ``tags['USLT'] = ...`` assignment on
    # some mutagen versions.  ``delall('USLT')`` clears every USLT
    # frame so a single fresh ``add`` produces a clean single-frame
    # state.
    mf.tags.delall("USLT")
    mf.tags.add(USLT(encoding=3, lang="eng", desc="", text=plain_text))
    try:
        mf.save()
    except Exception as exc:
        LOG.warning("Failed to save ID3v2 USLT for %s: %s", audio_path, exc)
        return EmbedResult(
            supported=True, format="MP3", tag_name="USLT",
            status="error", error=str(exc),
        )
    return EmbedResult(
        supported=True, format="MP3", tag_name="USLT", status="embedded",
    )


def _embed_vorbis_comment(
    mf, audio_path: Path, plain_text: str, force: bool,
) -> EmbedResult:
    """Write into FLAC / OggVorbis / Opus ``LYRICS`` (Vorbis comment).

    Vorbis comments store every value as a list of strings, so
    ``mf['LYRICS'] = [plain_text]`` instead of the scalar assignment
    that APEv2 / ASF want. We deliberately don't dedupe down to
    ``[plain_text]`` if a multi-list already exists on save --
    ``mf[key] = [...]`` fully replaces the key.
    """
    key = "LYRICS"
    if mf.get(key) and not force:
        return EmbedResult(
            supported=True, format=type(mf).__name__, tag_name=key,
            status="skipped",
            error=f"{key} already present; pass --force to overwrite",
        )
    mf[key] = [plain_text]
    try:
        mf.save()
    except Exception as exc:
        LOG.warning(
            "Failed to save Vorbis %s for %s: %s", key, audio_path, exc,
        )
        return EmbedResult(
            supported=True, format=type(mf).__name__, tag_name=key,
            status="error", error=str(exc),
        )
    return EmbedResult(
        supported=True, format=type(mf).__name__, tag_name=key,
        status="embedded",
    )


def _embed_mp4(
    mf: MP4, audio_path: Path, plain_text: str, force: bool,
) -> EmbedResult:
    """Write into MP4 / M4A's standard ``\\xa9lyr`` atom.

    ``\\xa9lyr`` is the conventional MP4 lyrics atom read by foobar,
    iTunes, MusicBee (with the MP4 plugin), and JRiver. The
    visually similar ``\\xa9wrt`` is *writer/composer*, NOT lyrics --
    we deliberately write ``\\xa9lyr``.

    MP4 tags are list-of-strings, matching Vorbis comments rather
    than APEv2 scalars.
    """
    key = "\xa9lyr"
    if mf.get(key) and not force:
        return EmbedResult(
            supported=True, format="MP4", tag_name=key,
            status="skipped",
            error=f"{key} already present; pass --force to overwrite",
        )
    mf[key] = [plain_text]
    try:
        mf.save()
    except Exception as exc:
        LOG.warning(
            "Failed to save MP4 %s for %s: %s", key, audio_path, exc,
        )
        return EmbedResult(
            supported=True, format="MP4", tag_name=key,
            status="error", error=str(exc),
        )
    return EmbedResult(
        supported=True, format="MP4", tag_name=key, status="embedded",
    )


def _embed_asf(
    mf: ASF, audio_path: Path, plain_text: str, force: bool,
) -> EmbedResult:
    """Write into WMA's ``WM/Lyrics`` descriptor.

    Mutagen auto-encodes unicode descriptors (like ``WM/Lyrics``)
    as UTF-16LE -- the ASF spec mandates WCHAR strings inside the
    descriptor-storage stream -- so we hand it plain text and
    mutagen bins it as UTF-16LE on disk. We assign a single ``str``
    (not a list) because ASF descriptors are scalars.
    """
    key = "WM/Lyrics"
    if mf.get(key) and not force:
        return EmbedResult(
            supported=True, format="ASF", tag_name=key,
            status="skipped",
            error=f"{key} already present; pass --force to overwrite",
        )
    mf[key] = plain_text
    try:
        mf.save()
    except Exception as exc:
        LOG.warning(
            "Failed to save ASF %s for %s: %s", key, audio_path, exc,
        )
        return EmbedResult(
            supported=True, format="ASF", tag_name=key,
            status="error", error=str(exc),
        )
    return EmbedResult(
        supported=True, format="ASF", tag_name=key, status="embedded",
    )


def _embed_apev2(
    mf, audio_path: Path, plain_text: str, force: bool,
) -> EmbedResult:
    """Write into WavPack / APE's APEv2 ``LYRICS`` key.

    APEv2 stores strings as UTF-8 directly (no length-prefix
    encoding); ``mf['LYRICS'] = plain_text`` assigns a scalar (NOT
    a list-of-strings, which would persist as a multi-value APEv2
    tag and confuse some readers on multi-line lyrics).
    """
    key = "LYRICS"
    if mf.get(key) and not force:
        return EmbedResult(
            supported=True, format=type(mf).__name__, tag_name=key,
            status="skipped",
            error=f"{key} already present; pass --force to overwrite",
        )
    mf[key] = plain_text
    try:
        mf.save()
    except Exception as exc:
        LOG.warning(
            "Failed to save APEv2 %s for %s: %s", key, audio_path, exc,
        )
        return EmbedResult(
            supported=True, format=type(mf).__name__, tag_name=key,
            status="error", error=str(exc),
        )
    return EmbedResult(
        supported=True, format=type(mf).__name__, tag_name=key,
        status="embedded",
    )


__all__ = (
    "EmbedResult",
    "embed_lyrics",
)
